# Deleting CRD
# See link: https://github.com/helm/charts/blob/d58247103fafd5930792bb1fd3ac240547523200/stable/prometheus-operator/templates/prometheus-operator/cleanup-crds.yaml#L33
apiVersion: batch/v1
kind: Job
metadata:
  name: rook-post-delete
  # TODO: make serviceaccount
  namespace: kube-system
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "3"
    "helm.sh/hook-delete-policy": hook-succeeded
  labels:
    app: rook-post-delete
spec:
  template:
    metadata:
      name: rook-post-delete
      labels:
        app: rook-post-delete
    spec:
      serviceAccountName: default
      containers:
        - name: kubectl
          image: {{ .Values.images.hyperkube.repository }}:{{ .Values.images.hyperkube.tag }}
          imagePullPolicy: {{ .Values.images.hyperkube.pullPolicy }}
          command:
          - /bin/sh
          - -c
          - >
              kubectl delete crd cephblockpools.ceph.rook.io;
              kubectl delete crd cephclients.ceph.rook.io;
              kubectl delete crd cephclusters.ceph.rook.io;
              kubectl delete crd cephfilesystems.ceph.rook.io;
              kubectl delete crd cephnfses.ceph.rook.io;
              kubectl delete crd cephobjectstores.ceph.rook.io;
              kubectl delete crd cephobjectstoreusers.ceph.rook.io;
              kubectl delete crd objectbucketclaims.objectbucket.io;
              kubectl delete crd objectbuckets.objectbucket.io;
              kubectl delete crd volumes.rook.io;
      restartPolicy: OnFailure
